# Temporal service values
"{name}-db": postgres12
"{name}-dynamic-config-file": /etc/temporal/config/dynamicconfig/development.yaml
"{name}-log-level": warn
"{name}-address": "{name}:7233"
"{name}-cli-address": "{name}:7233"
