env_vars:
  - name: TEMPORAL_HOST
    key: temporal-host
    secret: false
    default: temporal
  - name: TEMPORAL_PORT
    key: temporal-port
    secret: false
    default: 7233
  - name: TEMPORAL_NAMESPACE
    key: temporal-namespace
    secret: false
    default: default
  - name: TEMPORAL_TASK_QUEUE
    key: temporal-task-queue
    secret: false
    default: main-task-queue
